/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "EmailCategorizationVpc": {
      "type": "sst.aws.Vpc"
    }
    "ImgProxyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ImgProxyKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ImgProxySalt": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ImgproxyService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "LogoDevPK": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LogoDevSK": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "OpenApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "categorize-email": {
      "name": string
      "type": "sst.aws.Function"
    }
    "categorized-emails-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "cdn-assets": {
      "bucketArn": string
      "bucketDomainName": string
      "bucketName": string
      "type": "aws.s3/bucketV2.BucketV2"
    }
    "cdn_distribution": {
      "distributionDomainName": string
      "distributionId": string
      "distributionOrigins": any
      "type": "aws.cloudfront/distribution.Distribution"
    }
    "consts": {
      "assistantId": string
      "domain": string
      "region": string
      "type": "sst.sst.Linkable"
    }
    "email-archive-s3": {
      "bucketArn": string
      "bucketDomainName": string
      "bucketName": string
      "type": "aws.s3/bucketV2.BucketV2"
    }
    "email-opensearch": {
      "accessPolicies": string
      "advancedOptions": {
      }
      "advancedSecurityOptions": {
        "anonymousAuthEnabled": boolean
        "enabled": boolean
        "internalUserDatabaseEnabled": boolean
        "masterUserOptions": {
          "masterUserArn": string
          "masterUserName": string
          "masterUserPassword": string
        }
      }
      "arn": string
      "clusterConfig": {
        "coldStorageOptions": {
          "enabled": boolean
        }
        "dedicatedMasterCount": number
        "dedicatedMasterEnabled": boolean
        "dedicatedMasterType": string
        "instanceCount": number
        "instanceType": string
        "multiAzWithStandbyEnabled": boolean
        "warmCount": number
        "warmEnabled": boolean
        "warmType": string
        "zoneAwarenessConfig": any
        "zoneAwarenessEnabled": boolean
      }
      "cognitoOptions": {
        "enabled": boolean
        "identityPoolId": string
        "roleArn": string
        "userPoolId": string
      }
      "domainEndpointOptions": {
        "customEndpoint": string
        "customEndpointCertificateArn": string
        "customEndpointEnabled": boolean
        "enforceHttps": boolean
        "tlsSecurityPolicy": string
      }
      "domainName": string
      "ebsOptions": {
        "ebsEnabled": boolean
        "iops": number
        "throughput": number
        "volumeSize": number
        "volumeType": string
      }
      "endpoint": string
      "type": "aws.opensearch/domain.Domain"
      "vpcOptions": any
    }
    "group-from-open-search": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "grouped-applications-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "grouping-DLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "grouping-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "incoming-rules": {
      "4dabf18193072939515e22adb298388d": string
      "id": string
      "packageVersion": string
      "urn": string
    }
    "open-api-processing-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "open-api-processing-queue-DLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "os-user-pool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "populate-from-s3": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "process-email": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "process-user-confirmation": {
      "name": string
      "type": "sst.aws.Function"
    }
    "sync-groups": {
      "name": string
      "type": "sst.aws.Function"
    }
    "sync-open-search": {
      "name": string
      "type": "sst.aws.Function"
    }
    "user-pool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "user-pool-client": {
      "id": string
      "secret": string
      "type": "aws.cognito/userPoolClient.UserPoolClient"
    }
    "user-pool-endpoint": {
      "endpoint": string
      "id": string
      "region": string
    }
    "users-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}